/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhofinaldepoo;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CJ
 */
public class Visualizar extends javax.swing.JFrame {

    private Cadastro telaCadastro;
    private ArrayList<TrabalhoFinalDePoo> array;
    
    
    public Visualizar() {
        initComponents();
        telaCadastro = new Cadastro(this);
        array = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButtonNovo = new javax.swing.JButton();
        jButtonVisualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonVisualizar.setText("Visualizar");
        jButtonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cpf", "T.Sang.", "Data/nasc.", "End.", "Cidade", "UF", "E-mail", "Tel.", "Cel."
            }
        ));
        jTable1.setRowSorter(null);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Nome");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Cpf");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("T.Sang.");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Data/nasc.");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("End.");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Cidade");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("UF");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("E-mail");
            jTable1.getColumnModel().getColumn(8).setHeaderValue("Tel.");
            jTable1.getColumnModel().getColumn(9).setHeaderValue("Cel.");
        }

        jLabel1.setText("Agenda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(613, Short.MAX_VALUE)
                .addComponent(jButtonNovo)
                .addGap(18, 18, 18)
                .addComponent(jButtonVisualizar)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluir)
                .addGap(43, 43, 43))
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonVisualizar)
                    .addComponent(jButtonExcluir))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarActionPerformed
        int linhaSelecionada;
        linhaSelecionada = jTable1.getSelectedRow();
        if (linhaSelecionada < 0){
            JOptionPane.showMessageDialog(this,"Por favor, selecione uma linha.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else{
            this.telaCadastro.mostrarDados(array.get(linhaSelecionada));
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonVisualizarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int selectIndex;
        selectIndex = jTable1.getSelectedRow();
        if (selectIndex < 0){
            JOptionPane.showConfirmDialog(this, "Por favor, selecione um ítem", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else{
            this.removeDadosDaTabela(selectIndex);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed
    
    public void addTrabalhoFinalDePoo(TrabalhoFinalDePoo t){
        this.array.add(t);
        this.addDadosNaTabela(t);
    }
    
    public void addDadosNaTabela (TrabalhoFinalDePoo t){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        SimpleDateFormat tt = new SimpleDateFormat("dd/MM/yyyy"); 
        String data = tt.format(t.getDataDeNascimento());
                
        model.addRow(new Object[]{t.getNome(), t.getCpf(), t.getTipoSanguineo(),data,t.getEndereco(),t.getCidade(), t.getUF(), t.getEmail(), t.getTelefone(), t.getCelular()});
         this.array.add(t);
    }
    
    public void removeDados(int i){
        array.remove(i);
        removeDadosDaTabela(i);
    }
    
    public void removeDadosDaTabela(int i){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.removeRow(i);
    }
    
    public void redesenhaTabela(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        while (model.getRowCount() > 0){
            model.removeRow(0);
        }
        for (TrabalhoFinalDePoo t: array){
            SimpleDateFormat tt = new SimpleDateFormat("dd/MM/yyyy"); 
            String data = tt.format(t.getDataDeNascimento());
            model.addRow(new Object[]{t.getNome(), t.getCpf(), t.getTipoSanguineo(),data,t.getEndereco(),t.getCidade(), t.getUF(), t.getEmail(), t.getTelefone(), t.getCelular()});
        }
    }
    
    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        this.telaCadastro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
